"""empty message

Revision ID: 264ed9fc83ca
Revises: None
Create Date: 2016-03-12 16:04:11.891854

"""

# revision identifiers, used by Alembic.
revision = '264ed9fc83ca'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('tag')
    op.drop_table('rel_merit')
    op.drop_table('rel_education')
    op.drop_table('rel_experience')
    op.drop_table('rel_language')
    op.drop_table('skilltype')
    op.drop_table('rel_workexperience')
    op.drop_table('rel_project')
    op.drop_table('cvprofile')
    op.drop_table('rel_publication')
    op.drop_table('localization')
    op.drop_table('rel_skill')
    op.alter_column('customer', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('education', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('education', 'education',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True)
    op.alter_column('education', 'school',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('education', 'title',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'education', 'profile', ['profile'], ['idprofile'])
    op.alter_column('experience', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('experience', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'experience', 'profile', ['profile'], ['idprofile'])
    op.alter_column('file', 'filename',
               existing_type=sa.NVARCHAR(length=72),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'conversation',
               existing_type=sa.NVARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'language',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'listening',
               existing_type=sa.NVARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'reading',
               existing_type=sa.NVARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'verbal',
               existing_type=sa.NVARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'writing',
               existing_type=sa.NVARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'language', 'profile', ['profile'], ['idprofile'])
    op.alter_column('merit', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('merit', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'merit', 'profile', ['profile'], ['idprofile'])
    op.add_column('profile', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('profile', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('profile', sa.Column('position', sa.String(length=128), nullable=True))
    op.alter_column('profile', 'firstname',
               existing_type=sa.NVARCHAR(length=72),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'profile', 'file', ['profilepicture'], ['idfile'])
    op.alter_column('project', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('project', 'hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('project', 'name',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'project', 'profile', ['profile'], ['idprofile'])
    op.create_foreign_key(None, 'project', 'customer', ['customer'], ['idcustomer'])
    op.alter_column('publication', 'authors',
               existing_type=sa.NVARCHAR(length=4000),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('publication', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('publication', 'title',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'publication', 'profile', ['profile'], ['idprofile'])
    op.alter_column('skill', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('skill', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'skill', 'profile', ['profile'], ['idprofile'])
    op.alter_column('user', 'email',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.NVARCHAR(length=128),
               nullable=True)
    op.create_foreign_key(None, 'user', 'profile', ['profile'], ['idprofile'])
    op.alter_column('workexperience', 'description',
               existing_type=sa.NVARCHAR(length=4000),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('workexperience', 'employer',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('workexperience', 'title',
               existing_type=sa.NVARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_foreign_key(None, 'workexperience', 'profile', ['profile'], ['idprofile'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workexperience', type_='foreignkey')
    op.alter_column('workexperience', 'title',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('workexperience', 'employer',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('workexperience', 'description',
               existing_type=sa.NVARCHAR(length=4000),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'password',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.alter_column('skill', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('skill', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'publication', type_='foreignkey')
    op.alter_column('publication', 'title',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('publication', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('publication', 'authors',
               existing_type=sa.NVARCHAR(length=4000),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.alter_column('project', 'name',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('project', 'hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.alter_column('project', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.alter_column('profile', 'firstname',
               existing_type=sa.NVARCHAR(length=72),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_column('profile', 'position')
    op.drop_column('profile', 'email')
    op.drop_column('profile', 'description')
    op.drop_constraint(None, 'merit', type_='foreignkey')
    op.alter_column('merit', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('merit', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.alter_column('language', 'writing',
               existing_type=sa.NVARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'verbal',
               existing_type=sa.NVARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'reading',
               existing_type=sa.NVARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'listening',
               existing_type=sa.NVARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'language',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('language', 'conversation',
               existing_type=sa.NVARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('file', 'filename',
               existing_type=sa.NVARCHAR(length=72),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.alter_column('experience', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('experience', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.alter_column('education', 'title',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('education', 'school',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('education', 'education',
               existing_type=sa.NVARCHAR(length=64),
               nullable=False)
    op.alter_column('education', 'description',
               existing_type=sa.NVARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('customer', 'name',
               existing_type=sa.NVARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.create_table('rel_skill',
    sa.Column('idrel_skill', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_skill', name='PK__rel_skil__59865C7A17053D2D')
    )
    op.create_table('localization',
    sa.Column('idlocalization', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.NVARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('en-us', sa.NVARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('sv', sa.NVARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idlocalization', name='PK__localiza__26277F8D0843A5A0')
    )
    op.create_table('rel_publication',
    sa.Column('idrel_publication', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_publication', name='PK__rel_publ__E835A756E7590EAE')
    )
    op.create_table('cvprofile',
    sa.Column('idcvprofile', sa.INTEGER(), nullable=False),
    sa.Column('profile', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idcvprofile', name='PK__cvprofil__E21CBE7C0346FAE2')
    )
    op.create_table('rel_project',
    sa.Column('idrel_project', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_project', name='PK__rel_proj__50849875263FB245')
    )
    op.create_table('rel_workexperience',
    sa.Column('idrel_workexperience', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workexperience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_workexperience', name='PK__rel_work__71383E09770F7306')
    )
    op.create_table('skilltype',
    sa.Column('idskilltype', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('localization', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idskilltype', name='PK__skilltyp__0989C1D4B3400C3B')
    )
    op.create_table('rel_language',
    sa.Column('idrel_language', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_language', name='PK__rel_lang__04D5F4B012C972DD')
    )
    op.create_table('rel_experience',
    sa.Column('idrel_experience', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_experience', name='PK__rel_expe__5C70D784FE3D9B15')
    )
    op.create_table('rel_education',
    sa.Column('idrel_education', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_education', name='PK__rel_educ__AB0968ECAF950160')
    )
    op.create_table('rel_merit',
    sa.Column('idrel_merit', sa.INTEGER(), nullable=False),
    sa.Column('idfield', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('merit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrel_merit', name='PK__rel_meri__F70FA48056EFDDA9')
    )
    op.create_table('tag',
    sa.Column('idtag', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.NVARCHAR(length=32), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('category', sa.NVARCHAR(length=16), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('profile', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idtag', name='PK__tag__2A4169E22020F1BC')
    )
    op.create_table('activity',
    sa.Column('idactivity', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('text', sa.NVARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idactivity', name='PK__activity__27B33FAC65A4E0AC')
    )
    ### end Alembic commands ###
