"""empty message

Revision ID: 82ef0c6b4625
Revises: None
Create Date: 2016-03-08 22:54:03.260617

"""

# revision identifiers, used by Alembic.
revision = '82ef0c6b4625'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('description', sa.String(length=4000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'description')
    ### end Alembic commands ###
